name: atril-mate
base: core22
adopt-info: atril-mate
summary: Lightweight and Powerful Document Reader from Mate Community.
description: |
  Atril is a Lightweight and Powerful Document Viewer.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
assumes: [snapd2.55]

plugs:
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo
    
slots:
  atril-mate:
    interface: dbus
    bus: session
    name: org.mate.atril-mate
    
apps:
  atril-mate:
    command: usr/bin/atril
    extensions: [gnome]
    common-id: org.mate.atril
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - cups
      - avahi-observe
      - network
      - network-bind
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      
  atril-previewer:
    command: usr/bin/atril-previewer
    plugs:
      - avahi-observe
      - cups
      - gsettings
      - home
      - network
      
  atril-thumbnailer:
    command: usr/bin/atril-thumbnailer
    plugs:
      - gsettings
      - home      

parts:
  atril-mate:
    source: https://github.com/mate-desktop/atril.git
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags) 
      
    build-packages:
      - curl
      - build-essential   
      - autopoint
      - clang
      - clang-tools
      - git
      - gobject-introspection
      - libcaja-extension-dev
      - libdjvulibre-dev
      - libgail-3-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libgxps-dev
      - libkpathsea-dev
      - libsynctex-dev
      - libpoppler-glib-dev
      - libsecret-1-dev
      - libsm-dev
      - libspectre-dev
      - libtiff-dev
      - libwebkit2gtk-4.0-dev
      - libx11-dev
      - libxml2-dev
      - lsb-release
      - make
      - mate-common
      - xsltproc
      - yelp-tools
      - zlib1g-dev
      
    override-build: |
      craftctl default
      curl -LO https://github.com/mate-desktop/atril/releases/download/v1.27.0/atril-1.27.0.tar.xz
      tar xf atril-1.27.0.tar.xz
      cd atril-1.27.0
      ./autogen.sh --prefix=/usr
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT PREFIX=/usr
      make PREFIX=/usr DESTDIR=${SNAPCRAFT_PART_INSTALL} install
    
    stage-packages:
      - libsynctex2
      - libdjvulibre21
      - libgs9 
      - libidn-dev
      - libidn12
      - libidn2-0
      - libijs-0.35
      - libjbig2dec0
      - libkpathsea6
      - libpaper-utils
      - libpaper1
      - libspectre1
      - libgxps2
      - libgxps-utils
      - libcaja-extension1
      
 
